name: Update commit hash
on:
  schedule:
    - cron: "0 0 * * *" # Every day at 00:00

jobs:
  change-commit:
    name: Change the commit hash to the latest upstream one
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change commit
        run: |
          hash=$(git ls-remote https://github.com/mmatyas/pegasus-frontend refs/tags/continuous | cut -f 1)
          sed -i "s/  commit: .*/  commit: $hash/" org.pegasus_frontend.Pegasus.yml
      - name: Push the change
        run: |
          git config user.name CI
          git config user.email ""
          git add org.pegasus_frontend.Pegasus.yml
          git commit -m "Update pegasus-frontend.git" || exit 0
          git push
